/* Generated by bin2c, do not edit manually */
#ifndef _____Resource_audio_please_repeat_h_included
#define _____Resource_audio_please_repeat_h_included

/* Contents of file ..\Resource\please_repeat.pcm */
#define ___Resource_please_repeat_pcm_size 43920
extern const unsigned char ___Resource_please_repeat_pcm[43920];

#endif    /* _____Resource_audio_please_repeat_h_included */
